<a href="https://colab.research.google.com/github/victormurcia/VCHAMPS/blob/main/VCHAMPS_Save_Updated_Mapped_Dataframes_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#General utilities
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm  # Import tqdm for the progress bar
import math
import glob,shutil,os,warnings,math,time,sys,re
from typing import List
import dask.dataframe as dd
from dask.diagnostics import ProgressBar

#For UUID generation
import uuid

#For Slider viz
import ipywidgets as widgets
from IPython.display import display, clear_output,HTML

#Enable data to be extracted and downloaded from my Google Drive
from google.colab import drive, files
drive.mount('/content/drive')

Mounted at /content/drive

# Conditions

In [2]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/conditions/*.parquet')
df = df.compute()
df

,Internalpatientid,Age at condition documentation,Condition documented date,Diagnosis sequence number or rank,Diagnosis,Problem,code,cc Status,Encounter ID
0,1,58,2002-03-03 21:37:12,S,True,False,M159,NCC,36c34b45-5879-4cc7-be9b-d733061e30a3
1,1,58,2002-03-03 21:37:12,S,True,False,M199,NCC,333ca061-57d1-4fb1-ab99-f142ead909a1
2,1,58,2002-03-03 21:37:12,P,True,False,I10,NCC,63a9f5d1-c77c-452c-9b7f-80e86f19d423
3,1,58,2002-03-03 21:37:12,S,True,False,E782,NCC,3e246aaa-2d6d-4d78-a489-db9ef2373d65
4,1,59,2002-11-23 13:29:02,S,True,False,E782,NCC,30ff0057-8fab-4c81-ac1b-034f8c8eedc1
...,...,...,...,...,...,...,...,...,...
99995,118516,60,2015-07-01 17:27:21,P,True,False,Z0389,NCC,3cf86993-a81b-57c3-964d-0857e5acd137
99996,118516,60,2015-08-27 09:05:27,P,True,False,Z0389,NCC,ae641a0f-f803-5d7c-aade-62e93064e42b
99997,118516,61,2016-03-28 11:17:25,P,True,False,Z0389,NCC,8e1c58fe-941f-521f-913e-5930bc72788f
99998,118516,62,2017-07-19 04:28:37,S,True,False,E660,NCC,802eefc5-514a-54bc-8fbf-ad5b9236e637
99999,118516,62,2017-07-19 04:28:37,S,True,False,I504,NCC,802eefc5-514a-54bc-8fbf-ad5b9236e637

In [3]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/conditions.parquet',index=False)

# Death

In [4]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/death.parquet')
df = df.compute()
df

,Internalpatientid,Age at death,Death date,Encounter ID
0,100036,72,2015-01-18 20:49:10,16bd7ce5-d934-47fc-b63c-fd46c1085255
1,100037,75,2008-10-16 15:14:26,6220a7fa-eaf1-4bd5-990d-05cf9d2fb91f
2,100045,85,2019-01-26 11:33:52,cabbb194-ac58-4af1-86bc-f09b3b2ff24e
3,100095,84,2004-08-10 21:49:35,abb7db7e-f966-4004-b637-14f752242009
4,10013,68,2007-06-11 00:17:06,bade2186-f426-459a-860b-25f51f6b228d
...,...,...,...,...
97279,99827,88,2003-05-13 23:58:55,7d1772f8-8212-4e7f-bbd9-e450d2860e42
97280,99842,78,2010-05-25 14:36:27,b62508d6-3f2f-41a9-8baa-074917f9af34
97281,99847,82,2012-02-20 05:44:33,6b9d465f-78e0-44c6-b40e-81022fe72c6f
97282,99872,93,2010-04-18 05:12:36,fae9236a-12b9-4061-b6ed-fed2cdfb1f15
97283,99999,96,2013-04-14 08:08:53,2dbc3289-9855-5a1e-91c9-87c6f1396c73

In [5]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/death.parquet',index=False)

# Demographics Static

In [6]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned/demographics_static.parquet/*.parquet')
df = df.compute()
df

,Internalpatientid,Ethnicity,Veteran flag,Female,Male,Asian,Asian ; Other,Black or African American,Black or African American ; Asian,Black or African American ; Other,Black or African American ; White,Black or African American ; White ; Asian,Black or African American ; White ; Other,Other,White,White ; Asian,White ; Asian ; Other,White ; Other
0,168674,Hispanic or Latino,1.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
1,168681,Not Hispanic or Latino,1.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
2,168696,Not Hispanic or Latino,1.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,168711,Not Hispanic or Latino,1.0,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False
4,168720,Not Hispanic or Latino,1.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133247,168624,Not Hispanic or Latino,1.0,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False
133248,168626,Not Hispanic or Latino,1.0,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False
133249,168628,Not Hispanic or Latino,1.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
133250,168645,Not Hispanic or Latino,1.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
133251,168661,Not Hispanic or Latino,1.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False

In [7]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/demographics_static.parquet',index=False)

# Demographics Event

In [8]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/demographics_event.parquet')
df = df.compute()
df

,Internalpatientid,Age at update,Event date,Divorced,Married,Never married,Separated,Single,Unknown,Widowed,Highly rural,Rural,Urban,Encounter ID
0,100028,79,2020-08-24 03:33:32,False,True,False,False,False,False,False,False,False,True,e0f58601-833e-5982-b624-175beb0cfc77
1,100032,91,2008-02-07 05:03:27,False,True,False,False,False,False,False,False,True,False,26960966-c254-5cdd-a22b-e4305f53dba4
2,100046,73,2003-09-14 09:32:12,False,True,False,False,False,False,False,False,False,True,0c514ba1-9295-4acd-b397-a07f3b76fb37
3,100071,75,2019-04-25 08:33:42,False,False,False,False,False,False,True,False,False,True,dd9f49d1-856a-4659-975a-6cb78622be7c
4,100091,81,2022-02-09 09:24:20,False,False,True,False,False,False,False,False,False,True,b747ba8a-8696-44a2-8f35-57a046e551d2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133247,99898,92,2014-05-12 13:01:07,False,True,False,False,False,False,False,False,False,True,3281f665-f906-42f4-a83a-272898de4763
133248,9995,80,2011-07-08 20:09:29,False,True,False,False,False,False,False,False,True,False,302180f8-67b4-420e-a7cb-30efd7065455
133249,99950,77,2005-12-14 22:21:25,False,True,False,False,False,False,False,False,False,True,3959fd06-b3f6-4982-9ec6-bd594de84193
133250,9998,62,2011-02-23 15:35:32,True,False,False,False,False,False,False,False,False,True,8304a1cb-b7c6-4d7f-880d-4e671e386c84
133251,9999,70,2022-11-20 11:19:29,False,True,False,False,False,False,False,False,False,True,a7aa66d3-b2ad-4f0b-97c7-f27ed277244f

In [9]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/demographics_event.parquet',index=False)

# Ed Visits

In [10]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/ed_visits.parquet')
df = df.compute()
df

,Internalpatientid,Age at ed visit,Ed visit start date,Discharge date ed,Died during ed visit,CV diagnosis,code,cc Status,Encounter ID
0,101689,64,2021-08-26 00:53:30,2021-08-26 04:24:27,0,1,I502,NCC,2afc637f-1e93-5ce7-b817-0784cebc77a1
1,101689,64,2021-08-26 00:53:30,2021-08-26 04:24:27,0,1,N189,NCC,2afc637f-1e93-5ce7-b817-0784cebc77a1
2,107210,71,2022-05-18 11:21:28,2022-05-18 18:30:21,0,0,A419,MCC,0d3f5146-915f-5e92-b3e0-0ea9f4aa0141
3,107210,71,2022-05-18 11:21:28,2022-05-18 18:30:21,0,0,I959,NCC,0d3f5146-915f-5e92-b3e0-0ea9f4aa0141
4,107866,61,2017-06-26 15:41:11,2017-06-26 23:33:50,0,0,R918,NCC,efb622f7-8c68-5b26-ae9f-09147ff0dce7
...,...,...,...,...,...,...,...,...,...
1099360,9883,90,2020-02-20 21:23:37,2020-02-20 22:56:30,0,0,W108,NCC,da0bbfb2-28fc-5b3a-afcb-2642eee54c6f
1099422,99235,87,2016-02-25 01:22:23,2016-02-25 06:33:45,0,0,R197,NCC,7c5682aa-be6e-5fca-8c73-ec208a0ac60f
1099538,99902,66,2018-09-28 23:21:41,2018-09-28 23:56:55,0,0,M796,NCC,15df3aab-aa5b-51fa-b993-2d1cad1fa444
1099548,99934,84,2022-07-22 09:19:20,2022-07-22 09:42:57,0,0,M796,NCC,b3f5f12b-57fd-5978-842e-8f8f8c293522
1099550,99936,72,2016-08-29 23:10:25,2016-08-30 01:43:36,0,0,M255,NCC,8e219044-f089-50b8-9474-f177d5ac1f9a

In [11]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/ed_visits.parquet',index=False)

# Immunizations

In [12]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/immunizations/*.parquet')
df = df.compute()
df

,Internalpatientid,Age at immunization,Immunization date,Immunization,Administered elsewhere,Cvx code,Series doses_1,Series doses_2,Series doses_3,Series doses_4,Series doses_5,Series doses_6,Series doses_Booster,Series doses_Complete,Series doses_NS,Series doses_Partial,Encounter ID
0,100000,64,2019-10-03 07:20:00,"PNEUMOCOCCAL, UNSPECIFIED FORMULATION",None,109,0,0,0,0,0,0,0,0,1,0,bf9d063d-7e36-471d-a7d3-a6d6caa8a868
1,100000,64,2019-10-03 07:20:00,"PNEUMOCOCCAL, UNSPECIFIED FORMULATION",None,109,0,0,0,0,0,0,0,0,1,0,89c6c23e-8870-4916-b191-762719975e0f
2,100000,64,2019-10-03 07:20:00,"PNEUMOCOCCAL, UNSPECIFIED FORMULATION",None,109,0,0,0,0,0,0,0,0,1,0,efc608ca-da88-40a2-bcc2-984823a6fac5
3,162877,98,2013-10-17 00:23:48,"FLU,3 YRS (HISTORICAL)",None,88,0,0,0,0,0,0,0,0,1,0,84b4b1e4-3ba9-4db4-ace7-526decfe726d
4,162877,98,2013-10-17 00:23:48,"FLU,3 YRS (HISTORICAL)",None,88,0,0,0,0,0,0,0,0,1,0,c3882f64-e336-4f17-8b6d-f8be316a4288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49762,162868,92,2020-11-29 05:20:37,ZOSTER RECOMBINANT,None,187,1,0,0,0,0,0,0,0,0,0,89953db5-2bab-5181-90ff-8ed9888e6df9
49763,162869,78,2007-03-16 22:39:20,ZZZINFLUENZA (HISTORICAL),None,88,0,0,0,0,0,0,0,0,1,0,cbcfeb4c-5e6c-482d-b2b2-128e18419831
49764,162875,60,2010-11-27 21:25:26,TD(ADULT) UNSPECIFIED FORMULATION,None,139,0,0,0,0,0,0,0,0,1,0,5cabab3d-4e89-48bb-a396-1466c1f53675
49765,162877,91,2007-01-24 05:40:58,TD(ADULT) UNSPECIFIED FORMULATION,None,139,0,0,0,0,0,0,0,0,1,0,e94b7fb5-a8cb-4c09-be4d-6f8ea44386f6
49766,162877,98,2013-10-17 00:23:48,"INFLUENZA, UNSPECIFIED FORMULATION",None,88,0,0,0,0,0,0,0,0,1,0,5997a588-beb2-498a-8a0d-a265d7f00382

In [13]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/immunizations.parquet',index=False)

# Inpatient Admissions

In [34]:
inpatient_admissions = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/inpatient_admissions.parquet')
inpatient_admissions = inpatient_admissions.compute()
inpatient_admissions

,Internalpatientid,Age at admission,Admission date,Discharge date,Admitting unit service,Discharging unit service,Admitting specialty,Discharging specialty,Died during admission,Outpatientreferralflag,...,cc Status_CC,cc Status_MCC,cc Status_NCC,Discharge disposition_Death with autopsy,Discharge disposition_Death without autopsy,Discharge disposition_Irregular,Discharge disposition_NBC or while ASIH,Discharge disposition_Regular,Discharge disposition_Transfer,Encounter ID
0,10,66,2015-11-28 17:41:09,2015-11-29 01:43:14,NON-COUNT,NON-COUNT,DRUG DEPENDENCE TRMT UNIT,MEDICAL OBSERVATION,0,0,...,0,1,0,0,0,0,0,1,0,974dbd04-1e56-59c6-a720-b8784dc604b2
1,10,66,2015-11-28 17:41:09,2015-11-29 01:43:14,NON-COUNT,NON-COUNT,DRUG DEPENDENCE TRMT UNIT,MEDICAL OBSERVATION,0,0,...,0,0,1,0,0,0,0,1,0,974dbd04-1e56-59c6-a720-b8784dc604b2
2,100001,84,2009-10-01 21:19:50,2009-10-04 16:51:33,MEDICINE,MEDICINE,PSYCHIATRIC MENTALLY INFIRM,GENERAL(ACUTE MEDICINE),0,1,...,0,1,0,0,0,0,0,1,0,c86658fc-cb34-536f-bf7c-a6a05ad131cc
3,100001,84,2009-10-01 21:19:50,2009-10-04 16:51:33,MEDICINE,MEDICINE,PSYCHIATRIC MENTALLY INFIRM,GENERAL(ACUTE MEDICINE),0,1,...,0,0,1,0,0,0,0,1,0,c86658fc-cb34-536f-bf7c-a6a05ad131cc
4,100001,85,2010-11-10 04:32:39,2010-11-19 08:49:45,SURGERY,SURGERY,SUBSTANCE ABUSE RES TRMT PROG,ORTHOPEDIC,0,0,...,0,0,1,0,0,0,0,1,0,9b0880c7-906a-5869-9bbb-698c6183bdec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085813,99975,89,2018-01-05 00:59:05,2018-01-06 23:18:39,NON-COUNT,NON-COUNT,PODIATRY,MEDICAL OBSERVATION,0,0,...,0,0,1,0,0,0,0,1,0,95223157-498c-5de5-a061-13d1e9ae985a
1085814,99986,73,2019-06-26 19:47:10,2019-06-29 21:18:00,MEDICINE,MEDICINE,INTERMEDIATE MEDICINE,GENERAL(ACUTE MEDICINE),0,1,...,0,0,1,0,0,0,0,1,0,bd343752-5059-5181-81ad-dd066c9179c3
1085815,99986,73,2019-06-26 19:47:10,2019-06-29 21:18:00,MEDICINE,MEDICINE,INTERMEDIATE MEDICINE,GENERAL(ACUTE MEDICINE),0,1,...,0,0,1,0,0,0,0,1,0,bd343752-5059-5181-81ad-dd066c9179c3
1085816,99994,83,2016-08-13 20:09:52,2016-08-15 16:43:07,SURGERY,MEDICINE,INTERMEDIATE MEDICINE,GENERAL(ACUTE MEDICINE),0,1,...,1,0,0,0,0,0,0,1,0,a0b6452b-5012-5b06-81f3-150b3a92b656
1085817,99994,83,2016-08-13 20:09:52,2016-08-15 16:43:07,SURGERY,MEDICINE,INTERMEDIATE MEDICINE,GENERAL(ACUTE MEDICINE),0,1,...,0,1,0,0,0,0,0,1,0,a0b6452b-5012-5b06-81f3-150b3a92b656

In [36]:
#Rename column of outcome variable
inpatient_admissions.rename(columns={"Died during admission": "mortality_inhosp_allcause"}, inplace=True)

#Get hospital readmissions
counts_df = inpatient_admissions.groupby(['Internalpatientid', 'Admission date', 'Discharge date']).size().reset_index(name='Count')
aggregated_counts_df = counts_df.groupby('Internalpatientid')['Count'].sum()
aggregated_counts_df = aggregated_counts_df.to_frame().reset_index()
merged_df = inpatient_admissions.merge(aggregated_counts_df, on='Internalpatientid', how='left')
merged_df.rename(columns={"Count": "rehosp_allcause"}, inplace=True)
merged_df['rehosp_allcause'] = np.where(merged_df['rehosp_allcause'] > 1, 1, 0)

#Mortality PostHospitalization for Different Windows (30,90,180,365 days)
death_df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned/death.parquet')
death_df = death_df.compute()
hospitalizations_df = merged_df
merged_df = hospitalizations_df.merge(death_df, on='Internalpatientid', how='left')
merged_df['mortality_posthosp_30d'] = ((merged_df['mortality_inhosp_allcause'] == 0) & ((merged_df['Death date'] - merged_df['Discharge date']).dt.days < 30)).astype(int)
merged_df['mortality_posthosp_90d'] = ((merged_df['mortality_inhosp_allcause'] == 0) & ((merged_df['Death date'] - merged_df['Discharge date']).dt.days < 90)).astype(int)
merged_df['mortality_posthosp_180d'] = ((merged_df['mortality_inhosp_allcause'] == 0) & ((merged_df['Death date'] - merged_df['Discharge date']).dt.days < 180)).astype(int)
merged_df['mortality_posthosp_365d'] = ((merged_df['mortality_inhosp_allcause'] == 0) & ((merged_df['Death date'] - merged_df['Discharge date']).dt.days < 365)).astype(int)
hospitalization_df = merged_df

#All Cause Readmission
grouped_df = hospitalizations_df.groupby(['Internalpatientid', 'Admission date', 'Discharge date']).size().reset_index(name='Count')
# Sort the DataFrame by Internalpatientid and Admission date
grouped_df = grouped_df.sort_values(['Internalpatientid', 'Admission date'])
# Create a new column Prev_Discharge with the previous row's Discharge date
grouped_df['Prev_Discharge'] = grouped_df.groupby('Internalpatientid')['Discharge date'].shift()
# Calculate the time difference between Prev_Discharge and Admission date
grouped_df['Time_Passed'] = (grouped_df['Admission date'] - grouped_df['Prev_Discharge']).dt.days
# Drop rows with NaN and NaT values in the Time_Passed column
grouped_df = grouped_df.dropna(subset=['Time_Passed'])
# Drop rows with Time_Passed equal to -1
grouped_df = grouped_df[grouped_df['Time_Passed'] != -1]
# Convert Time_Passed column to integer (days)
grouped_df['Time_Passed'] = grouped_df['Time_Passed'].astype(int)
smallest_time_passed = grouped_df.groupby('Internalpatientid')['Time_Passed'].min()
smallest_time_passed_df = smallest_time_passed.reset_index(name='Smallest Time Passed')
smallest_time_passed_df['readmit_allcause_30d'] = np.where(smallest_time_passed_df['Smallest Time Passed'] < 30, 1, 0)
smallest_time_passed_df['readmit_allcause_90d'] = np.where(smallest_time_passed_df['Smallest Time Passed'] < 90, 1, 0)
smallest_time_passed_df['readmit_allcause_180d'] = np.where(smallest_time_passed_df['Smallest Time Passed'] < 180, 1, 0)
smallest_time_passed_df['readmit_allcause_365d'] = np.where(smallest_time_passed_df['Smallest Time Passed'] < 365, 1, 0)
merged_df = hospitalizations_df.merge(smallest_time_passed_df, on='Internalpatientid', how='left')
hospitalizations_df = merged_df

#CV Readmissions
hospitalizations_df['readmit_CV_30d']  = np.where((hospitalizations_df['CV diagnosis'] == 1) & (hospitalizations_df['readmit_allcause_30d'] == 1), 1, 0)
hospitalizations_df['readmit_CV_90d']  = np.where((hospitalizations_df['CV diagnosis'] == 1) & (hospitalizations_df['readmit_allcause_90d'] == 1), 1, 0)
hospitalizations_df['readmit_CV_180d'] = np.where((hospitalizations_df['CV diagnosis'] == 1) & (hospitalizations_df['readmit_allcause_180d'] == 1), 1, 0)
hospitalizations_df['readmit_CV_365d'] = np.where((hospitalizations_df['CV diagnosis'] == 1) & (hospitalizations_df['readmit_allcause_365d'] == 1), 1, 0)

#CV Inhospital Mortality
hospitalizations_df['mortality_inhosp_CV']  = np.where((hospitalizations_df['CV diagnosis'] == 1) & (hospitalizations_df['mortality_inhosp_allcause'] == 1), 1, 0)
hospitalizations_df

,Internalpatientid,Age at admission,Admission date,Discharge date,Admitting unit service,Discharging unit service,Admitting specialty,Discharging specialty,mortality_inhosp_allcause,Outpatientreferralflag,...,Smallest Time Passed,readmit_allcause_30d,readmit_allcause_90d,readmit_allcause_180d,readmit_allcause_365d,readmit_CV_30d,readmit_CV_90d,readmit_CV_180d,readmit_CV_365d,mortality_inhosp_CV
0,10,66,2015-11-28 17:41:09,2015-11-29 01:43:14,NON-COUNT,NON-COUNT,DRUG DEPENDENCE TRMT UNIT,MEDICAL OBSERVATION,0,0,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
1,10,66,2015-11-28 17:41:09,2015-11-29 01:43:14,NON-COUNT,NON-COUNT,DRUG DEPENDENCE TRMT UNIT,MEDICAL OBSERVATION,0,0,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
2,100001,84,2009-10-01 21:19:50,2009-10-04 16:51:33,MEDICINE,MEDICINE,PSYCHIATRIC MENTALLY INFIRM,GENERAL(ACUTE MEDICINE),0,1,...,63.0,0.0,1.0,1.0,1.0,0,0,0,0,0
3,100001,84,2009-10-01 21:19:50,2009-10-04 16:51:33,MEDICINE,MEDICINE,PSYCHIATRIC MENTALLY INFIRM,GENERAL(ACUTE MEDICINE),0,1,...,63.0,0.0,1.0,1.0,1.0,0,0,0,0,0
4,100001,85,2010-11-10 04:32:39,2010-11-19 08:49:45,SURGERY,SURGERY,SUBSTANCE ABUSE RES TRMT PROG,ORTHOPEDIC,0,0,...,63.0,0.0,1.0,1.0,1.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001358,99975,89,2018-01-05 00:59:05,2018-01-06 23:18:39,NON-COUNT,NON-COUNT,PODIATRY,MEDICAL OBSERVATION,0,0,...,12.0,1.0,1.0,1.0,1.0,0,0,0,0,0
1001359,99986,73,2019-06-26 19:47:10,2019-06-29 21:18:00,MEDICINE,MEDICINE,INTERMEDIATE MEDICINE,GENERAL(ACUTE MEDICINE),0,1,...,0.0,1.0,1.0,1.0,1.0,0,0,0,0,0
1001360,99986,73,2019-06-26 19:47:10,2019-06-29 21:18:00,MEDICINE,MEDICINE,INTERMEDIATE MEDICINE,GENERAL(ACUTE MEDICINE),0,1,...,0.0,1.0,1.0,1.0,1.0,0,0,0,0,0
1001361,99994,83,2016-08-13 20:09:52,2016-08-15 16:43:07,SURGERY,MEDICINE,INTERMEDIATE MEDICINE,GENERAL(ACUTE MEDICINE),0,1,...,28.0,1.0,1.0,1.0,1.0,0,0,0,0,0
1001362,99994,83,2016-08-13 20:09:52,2016-08-15 16:43:07,SURGERY,MEDICINE,INTERMEDIATE MEDICINE,GENERAL(ACUTE MEDICINE),0,1,...,28.0,1.0,1.0,1.0,1.0,0,0,0,0,0

In [37]:
hospitalizations_df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/inpatient_admissions.parquet',index=False)

# Inpatient Location

In [16]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/inpatient_location.parquet')
df = df.compute()
df

,Internalpatientid,Age at location,Location start date,Location end date,Service,Died at location,Encounter ID
0,100005,66,2002-09-09 01:24:31,2002-09-12 01:00:40,MEDICINE,0,6acbda18-63a1-5086-a5f2-64bbb198632e
1,100008,70,2019-06-04 05:46:59,2019-06-05 10:07:31,SURGERY,0,ef5e041b-4e3a-5cba-afa8-de036ba335d4
2,100015,55,2001-04-01 01:32:23,2001-04-02 20:04:22,MEDICINE,0,c90d9a73-08d3-5217-aa5f-69225425b1eb
3,100015,56,2001-07-29 20:19:52,2001-07-30 22:42:13,MEDICINE,0,bdcc756b-a0be-509c-aedd-f366602ee3a9
5,100026,61,2017-04-22 12:58:18,2017-04-25 03:43:53,MEDICINE,0,c8750041-50d2-5e6c-8587-a641615a1182
...,...,...,...,...,...,...,...
850032,99974,53,2003-08-25 17:35:48,2003-08-31 15:18:56,MEDICINE,0,89bfbaf3-d368-4ca5-b5bd-cd8f08e891b7
850033,99981,67,2009-08-21 05:12:20,2009-08-24 07:10:02,SURGERY,0,72f1a0a9-3887-5b36-9c34-7fa4bc871441
850034,99983,44,2006-04-22 23:06:15,2006-04-29 13:25:45,DOMICILIARY,0,ced196f3-133d-59a9-9040-9b3601fa2189
850035,9999,61,2013-09-14 10:54:27,2013-09-15 06:16:09,SURGERY,0,eaf7690b-8b9d-5a21-ab1b-ae476aa4b7ce
850036,99992,55,2010-04-10 20:43:55,2010-04-13 00:29:27,SURGERY,0,05dceb3a-fbc7-5416-bb43-2df5b50bfb0a

In [17]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/inpatient_location.parquet',index=False)

# Inpatient Specialty

In [18]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/inpatient_specialty.parquet')
df = df.compute()
df

,Internalpatientid,Age at specialty,Specialty start date,Specialty end date,Specialty,Encounter ID
0,1,79,2022-12-31 05:41:51,2023-01-01 23:06:29,DERMATOLOGY,e8f395d3-c8d4-5cf4-a686-34352c9e47c3
1,100001,87,2012-07-21 23:00:00,2012-07-22 19:18:47,PM&R TRANSITIONAL REHAB,13f5cb00-3104-519d-89ef-33c7a85f2de8
2,100015,57,2002-07-16 06:40:13,2002-07-16 06:40:13,INTERMEDIATE MEDICINE,7348e73e-71bd-404f-bf10-177f0d249226
3,100015,58,2004-02-21 11:01:35,2004-02-22 14:56:40,DOMICILIARY PTSD,da52c625-e2bd-5031-ba84-a938baa4f96e
4,100019,81,1999-10-24 10:44:24,1999-10-31 10:20:31,PLASTIC SURGERY,fba82c7b-9bf6-599e-85cb-c65ed3831022
...,...,...,...,...,...,...
725466,99993,58,2007-02-18 00:35:16,2007-02-18 04:55:16,METABOLIC,ec0d7f6c-983e-5aa9-8474-d948f36a52f4
725467,99994,83,2016-10-18 10:35:16,2016-10-21 11:02:57,NH SHORT STAY DEMENTIA CARE,4b258fe8-25ab-57b4-8485-8313022fc335
725468,99994,86,2019-08-30 08:38:03,2019-09-05 09:28:48,"PULMONARY, NON-TB",c3900bc9-5e28-5def-8584-7f06a5bd9be3
725469,99996,56,2011-08-17 00:10:52,2011-08-17 00:10:52,GENERAL(ACUTE MEDICINE),502e87d1-488b-4849-bc7f-a7845e8966af
725470,99999,96,2013-04-04 20:44:37,2013-04-14 10:02:00,GEM PSYCHIATRIC BEDS,2dbc3289-9855-5a1e-91c9-87c6f1396c73

In [19]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/inpatient_specialty.parquet',index=False)

# Lab Measurements

In [20]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/lab_results/*.parquet')
df = df.compute()
df

,Internalpatientid,Age at lab test,Lab test date,Result numeric,Specimen source,desc,concept,unit,range_min,range_max,Encounter ID
0,23511,66,2013-05-13 19:58:45,143.000000,serum,ZSODIUM,na,mmol/L,136.0,145.0,75e105d9-27db-4639-bfd9-99214f43e737
1,23511,66,2013-06-21 17:21:08,144.000000,serum,ZSODIUM,na,mmol/L,136.0,145.0,4222f6a7-8023-40a5-ad10-58e043a47822
2,23256,51,2001-06-24 23:17:28,137.000000,serum,ZSODIUM,na,mmol/L,136.0,148.0,b3668b28-653c-5488-bb46-f5dd14ba103a
3,23256,56,2006-05-20 02:08:17,149.000000,serum,ZSODIUM,na,mmol/L,136.0,148.0,f29cb959-d880-5e6f-ba16-0d0bec5af545
4,23256,60,2010-04-08 10:26:51,140.000000,serum,ZSODIUM,na,mmol/L,136.0,148.0,bdb1bb2d-215a-502b-b2b8-3b2cd2d51939
...,...,...,...,...,...,...,...,...,...,...,...
99995,63089,48,2016-10-02 16:06:02,3.733482,plasma,POTASSIUM,k,mmol/L,3.5,4.7,c659f854-9090-4c5c-885a-3d042ca17392
99996,63089,48,2016-10-21 11:43:27,3.779337,plasma,POTASSIUM,k,mmol/L,3.5,4.7,a0b81727-15f0-56f3-8c67-349a90fcd750
99997,63089,52,2020-12-07 20:45:19,3.297369,plasma,POTASSIUM,k,mmol/L,3.5,4.7,616e63f6-f023-510a-8916-0d8f6498dbaf
99998,63092,63,2015-11-15 02:29:59,5.000000,serum,POTASSIUM,k,mmol/L,3.5,5.3,a7a9b46b-5451-5108-8f4b-a7a168d2a381
99999,63094,70,1997-01-25 09:23:04,4.492427,serum,POTASSIUM,k,mmol/L,3.3,5.1,327bf36a-c617-423d-8803-d26978faed78

In [21]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/lab_results.parquet',index=False)

# Measurements

In [22]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/measurements/*.parquet')
df = df.compute()
df

,Internalpatientid,Age at measurement,Measurement date,Measurement,Result numeric,Encounter ID
0,1,59,2003-05-21 00:27:01,Temperature,95.804066,0ca96b3d-9cca-461d-ba94-b1e8fe8ecfff
1,9713,68,2017-08-17 18:10:50,Pulse oximetry,88.000000,2395b56a-b7db-5a4b-869f-5ae3bcc11ee6
2,97124,72,2019-02-09 17:56:52,Pulse,66.000000,a06f4802-c63a-562f-9160-4a65241f4d7e
3,107718,63,2020-12-16 02:10:45,Temperature,95.979629,e158e91c-6384-5b83-8178-dceb8893a91c
4,96334,72,2016-01-09 06:23:49,Height,68.793928,8f78627d-d7da-5da5-bdf8-63bdc3d9e132
...,...,...,...,...,...,...
99995,104919,64,2011-12-05 03:36:17,Pulse oximetry,95.000000,c23052d5-b75d-59ba-b95b-03ce5267af00
99996,74324,68,2018-07-15 17:45:10,Pulse oximetry,92.000000,0766f3e3-e58d-435d-810d-f0c45cf5bcca
99997,17491,91,2019-06-16 14:54:43,Pulse,56.000000,e3b11345-e152-5de3-853e-315942252b04
99998,47056,76,2022-08-06 07:26:05,Temperature,100.933943,b5990f68-a97c-5e23-af1e-e20cac89e8b4
99999,162146,49,2014-06-29 21:10:09,Pulse,79.000000,655c81bf-002c-585c-8f16-0ecb3f040c0e

In [23]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/measurements.parquet',index=False)

# Measurements BP

In [24]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/measurements_bp/*.parquet')
df = df.compute()
df

,Internalpatientid,Age at measurement bp,Measurement date,Diastolic bp,Systolic bp,Encounter ID
0,83189,54,2005-02-28 05:05:34,79,120,7f635061-7d06-532d-b462-3bc8a46e67b6
1,61042,67,2018-03-27 19:03:44,62,113,d8b5ec41-4e49-593c-9226-0de174393e8e
2,55393,52,2015-11-04 04:24:23,83,125,5743ef1c-5dc2-5e45-ad6f-2c26e74f6402
3,45845,54,2017-07-02 13:54:24,84,153,790a7d0f-7de1-5f8e-a41c-ee3197ce254e
4,103234,73,2017-04-08 10:43:34,71,151,b05eca39-4261-4f51-9646-010cbac1b5d6
...,...,...,...,...,...,...
9995,130060,78,2011-08-14 13:55:25,85,181,3d00e426-3f95-53b6-b9b4-72ae70be56f0
9996,144793,52,2018-01-11 22:44:02,72,105,d761ab81-f7f9-4aad-ae62-db7e65da9626
9997,62421,67,2007-01-24 04:18:55,79,144,ebcb336a-f816-4e01-b856-cdbeeee41cef
9998,141195,61,2007-04-24 16:21:11,73,136,91d4f847-f532-4964-a229-5afc9fccd4f1
9999,27904,75,2013-07-13 20:30:39,51,126,e95d87ee-ccc8-4be3-be5c-6f41c4b06475

In [25]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/measurements_bp.parquet',index=False)

# Medications Administered

In [26]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/medications_administered/*.parquet')
df = df.compute()
df

,Internalpatientid,Age at med administration,Administration date,Administration end date,Administered medication atc 5,Administration status,Dose form,Dose administered,Dose unit administered,Encounter ID
0,78275,76,2013-01-21 14:30:39,NaT,omeprazole,Given,"cap,ec",1.0,"cap,ec",6a0188e5-a4fe-5a56-bdfe-27b4533ccd40
1,22855,60,2014-11-06 16:55:00,NaT,morphine,Given,"tab,sa",1.0,"tab,sa",43b79e98-a3d6-5e3b-9a5a-a60da5eb77cd
2,12315,68,2012-07-26 11:02:41,NaT,salbutamol,Given,"soln,inhl",1.0,1 vial.,c2e35837-314c-55fb-b128-ab9a373eafb7
3,109168,85,2009-08-15 06:53:27,NaT,docusate,Given,"cap,oral",1.0,"cap,oral",d88f24c6-cf99-46a6-8294-193a517dfb7e
4,106286,83,2004-08-23 04:50:23,NaT,hydrocortisone,Given,"dressing,top",1.0,1,20da8c77-2d53-4cda-bb15-317505117ff8
...,...,...,...,...,...,...,...,...,...,...
9995,147263,84,2017-02-22 18:47:29,NaT,baclofen,Given,tab,1.0,tab,141cb469-766b-471b-bb22-f9dade0c606f
9996,9585,78,2023-07-05 21:09:57,NaT,gabapentin,Given,"cap,oral",2.0,"cap,oral",608f1bcf-2fee-57fb-bf66-2a762dcaee1c
9997,124394,69,2019-01-29 13:36:32,NaT,piperacillin ; tazobactam,Given,inj,98.0,ML,edd6da11-7049-5ab5-873e-7d0d7cdf08c9
9998,68915,48,2009-02-05 13:32:25,NaT,paracetamol (acetaminophen),Given,"supp,rtl",1.0,650mg,4c66fca7-e938-5ce7-a141-c46b4b300d37
9999,73699,69,2016-08-04 11:43:55,NaT,enalapril,Given,tab,1.0,tab,911a30bd-7443-4826-bcdb-39bbc43dd732

In [27]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/medications_administered.parquet',index=False)

# Medications Ordered

In [28]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/medications_ordered/*.parquet')
df = df.compute()
df

,Internalpatientid,Age at med ordered,Order date,Medication start date,Medication stop date,Order discontinue date,Ordered medication atc 5,Order status,Stop reason,Encounter ID
0,122253,54,2001-08-08 00:07:03,2001-08-07 12:08:03,2002-08-08 12:08:03,NaT,hypromellose,expired,Not specified (no value),f3d3e234-4d72-4eb8-84c8-55350ced635b
1,98801,63,2013-08-23 15:41:00,2013-09-15 23:08:00,2014-01-03 23:08:00,2014-01-04 17:04:00,docusate,discontinued,Not specified (no value),b8508771-ddd3-4b74-825c-f2fb6e5c4f06
2,61915,64,2011-08-02 01:21:00,2011-08-01 17:07:00,2012-08-01 17:07:00,NaT,furosemide,expired,Not specified (no value),a2a885ac-a147-4155-ab65-b8c3450f3a81
3,46322,43,2003-06-07 11:39:47,2003-06-06 17:07:47,2004-05-27 17:07:47,2004-07-11 05:16:47,thiamine (vitamin b1),discontinued,Not specified (no value),17815e91-05bc-4da4-8665-4392e8ed8acc
4,152671,60,2002-11-18 12:22:00,2002-11-18 12:22:00,2002-11-18 03:52:00,2002-11-18 12:23:00,codeine ; paracetamol (acetaminophen),cancelled,Not specified (no value),08fd283e-e3c4-46b5-a484-b091d29aebd5
...,...,...,...,...,...,...,...,...,...,...
9995,53555,49,2011-07-22 22:56:03,2011-08-05 16:25:03,2011-08-06 04:25:03,NaT,clindamycin,expired,Not specified (no value),f4c1353f-2d76-4b5e-b4b1-e51ea8a21500
9996,137102,66,2016-06-14 06:28:30,2016-06-27 13:29:30,2016-07-09 13:29:30,2016-07-10 09:33:30,morphine,discontinued,Not specified (no value),c3a2bec1-619e-478f-8123-35d645a75160
9997,5661,72,2008-04-14 09:45:02,2008-04-14 11:26:02,2008-04-23 11:12:02,2008-04-23 11:12:02,acetylsalicylic acid,discontinued,Not specified (no value),4f52376e-387b-5630-91bc-b4869efe60a3
9998,131123,61,2012-11-05 11:51:15,2013-01-25 02:12:15,2013-10-13 02:12:15,2013-10-13 16:27:15,metformin,discontinued,Not specified (no value),3efedcad-fce8-4354-bd4a-9da51f91f219
9999,89612,73,2001-11-06 10:57:05,2001-11-14 19:57:05,2002-01-16 10:11:05,2002-01-16 10:11:05,ipratropium bromide ; salbutamol,discontinued,Not specified (no value),94e22ad7-4d9c-45f9-be22-1d6f8b5e74ad

In [29]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/medications_ordered.parquet',index=False)

# Outpatient Visits

In [30]:
df = dd.read_parquet('/content/drive/MyDrive/VCHAMPS - Train Cleaned-Mapped/outpatient_visits.parquet')
df = df.compute()
df

,Internalpatientid,Age at visit,Visit start date,Visit End Date,Stop code,Agentorangeflag,Combatflag,Ionizingradiationflag,Serviceconnectedflag,Swasiaconditionsflag,diagnosis,code,cc Status,Encounter ID
0,10037,57,2014-06-17 11:56:20,2014-06-17 13:56:20,EKG,NaN,NaN,NaN,NaN,NaN,other hypertrophic cardiomyopathy,I422,CC,7ca25b58-b33a-57a1-83c1-7fab40faaaff
0,65015,67,2018-06-21 01:25:05,2018-06-21 03:25:05,OPTOMETRY,NaN,NaN,NaN,No,NaN,type 2 diabetes mellitus without complications,E119,NCC,2631ee2b-20a4-5b72-bc1f-ff7c8e4589dd
0,6139,74,2022-07-14 21:44:44,2022-07-14 23:44:44,HT NON-VIDEO MONITORING,NaN,NaN,NaN,Yes,NaN,type 2 diabetes mellitus with unspecified comp...,E118,NCC,2c2ca169-48b0-5fce-bfe5-d0786a534457
0,18667,89,2021-03-22 11:41:03,2021-03-22 13:41:03,HOSPITAL IN HOME,NaN,NaN,NaN,NaN,NaN,chronic atrial fibrillation,I482,NCC,2fc52270-9dde-554c-a79d-81022ad98b67
0,77347,64,2019-07-03 13:45:28,2019-07-03 15:45:28,PRIMARY CARE/MEDICINE,NaN,NaN,NaN,Yes,NaN,kidney transplant status,Z940,CC,0afb8078-9f9b-50cf-b0d8-397ad8b01805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054843,10037,57,2014-05-07 15:00:57,2014-05-07 17:00:57,TELEPHONE/MEDICINE,NaN,NaN,NaN,NaN,NaN,type 2 diabetes mellitus with ophthalmic compl...,E113,NCC,0f2852c3-7975-5250-8a19-cc0fc47eba3a
1054845,10037,57,2014-05-16 06:07:53,2014-05-16 08:07:53,PRIMARY CARE/MEDICINE,NaN,NaN,NaN,NaN,NaN,dizziness and giddiness,R42,NCC,5c42cde4-5596-5ec4-944e-0608829d5835
1054846,10037,57,2014-05-16 06:07:53,2014-05-16 08:07:53,PRIMARY CARE/MEDICINE,NaN,NaN,NaN,NaN,NaN,type 2 diabetes mellitus with ophthalmic compl...,E113,NCC,5c42cde4-5596-5ec4-944e-0608829d5835
1054847,10037,57,2014-06-17 11:56:20,2014-06-17 13:56:20,PRIMARY CARE/MEDICINE,NaN,NaN,NaN,NaN,NaN,fracture of other and unspecified finger(s),S626,NCC,7ca25b58-b33a-57a1-83c1-7fab40faaaff
1054848,10037,57,2014-06-17 11:56:20,2014-06-17 13:56:20,PRIMARY CARE/MEDICINE,NaN,NaN,NaN,NaN,NaN,type 2 diabetes mellitus with ophthalmic compl...,E113,NCC,7ca25b58-b33a-57a1-83c1-7fab40faaaff

In [31]:
df.to_parquet('/content/drive/MyDrive/VCHAMPS - Final Train Data/outpatient_visits.parquet',index=False)